development:
  adapter: postgresql
  encoding: unicode
  database: zip_code_development
  pool: 30
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: zip_code_test
  pool: 5
  username: postgres
  password:
